name: Touch Leaderboard JSON

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch: {}      # let you run it manually

permissions:
  contents: write

jobs:
  touch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update timestamp in leaderboard.json
        run: |
          node -e '
            const fs = require("fs");
            const p = "leaderboard.json";
            const j = JSON.parse(fs.readFileSync(p, "utf8"));
            j.updated = new Date().toISOString();
            fs.writeFileSync(p, JSON.stringify(j, null, 2));
          '

      - name: Commit if changed
        run: |
          if [ -n "$(git status --porcelain leaderboard.json)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add leaderboard.json
            git commit -m "chore: auto-update leaderboard.json timestamp [skip ci]"
            git push
          else
            echo "No changes."
          fi
